name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mobius_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mobius_test" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=test-key" >> $GITHUB_ENV
        echo "ANTHROPIC_API_KEY=test-key" >> $GITHUB_ENV
        echo "SALESFORCE_CLIENT_ID=test-id" >> $GITHUB_ENV
        echo "SALESFORCE_CLIENT_SECRET=test-secret" >> $GITHUB_ENV
        echo "NETSUITE_BASE_URL=http://localhost:3001" >> $GITHUB_ENV
        echo "NETSUITE_ACCOUNT_ID=test-account" >> $GITHUB_ENV
        
    - name: Run database migrations
      run: npm run db:push
      
    - name: Build application
      run: npm run build
      
    - name: Run Playwright tests
      run: npm run test
      
    - name: Run API tests only
      run: npm run test:api
      
    - name: Run E2E tests only
      run: npm run test:e2e
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-videos
        path: test-results/
        retention-days: 30